const test = require("node:test");
const assert = require("node:assert/strict");

const expectedExportNames = [
  "acceptBookingRequestV3",
  "adminReplyToSupportTicket",
  "adminUpdateSupportTicketStatus",
  "applyUserRestriction",
  "assertSupportTicketAllowsAdminReply",
  "backfillSocialPostFeedMetadata",
  "backfillSocialPostHomeMetadata",
  "cancelBookingRequestByParentV3",
  "cancelConfirmedBookingByCustomerV3",
  "cancelConfirmedBookingByProviderV3",
  "changeUsername",
  "checkPhoneLoginEligibility",
  "closeChat",
  "completeBookingServiceV3",
  "completeOnboardingProfile",
  "createBookingDisputeV3",
  "createBookingQrPaymentV3",
  "createBookingRequestV3",
  "createOfferCampaign",
  "createRazorpayPaymentOrderV3",
  "createSocialNotification",
  "createSupportTicket",
  "declineBookingRequestV3",
  "deleteOfferCampaign",
  "evaluateOfferWallLaunch",
  "enqueueReportModeration",
  "enqueueServiceModeration",
  "expireAwaitingPaymentsV3",
  "expirePendingProviderBookingsV3",
  "finalizeCanonicalNoShowsV3",
  "finalizeCompletedBookingsV3",
  "finalizeSupportTicketAttachments",
  "getBookingFinancialLedgerV3",
  "getAvailableOffers",
  "getCanonicalBookingAdminDetailV3",
  "getCanonicalDisputeAdminDetailV3",
  "getCanonicalDisputeV3",
  "getCanonicalFinancialSummaryV3",
  "getCanonicalProviderPayoutAdminDetailV3",
  "getCanonicalRefundAdminDetailV3",
  "getNearbySocialPosts",
  "getProviderPayoutV3",
  "getProfileFollowCounts",
  "listCanonicalBookingsForAdminV3",
  "listCanonicalDisputesForAdminV3",
  "listCanonicalDisputesV3",
  "listCanonicalNoShowCasesV3",
  "listCanonicalProviderPayoutsForAdminV3",
  "listCanonicalRefundsForAdminV3",
  "listProviderPayoutsV3",
  "markBookingViewedByProviderV3",
  "markChatDelivered",
  "markChatRead",
  "markSupportTicketRead",
  "markSupportTicketReadAsAdmin",
  "moderateService",
  "pauseServicesForExpiredProviderVerification",
  "previewBookingCancellationV3",
  "previewBookingDisputeResolutionV3",
  "previewBookingPaymentPricingV3",
  "processProviderVerificationDocumentCleanup",
  "processScheduledAccountDeletions",
  "razorpayWebhook",
  "reconcileBookingPaymentsV3",
  "refreshSocialPostDiscoverScores",
  "removeNotificationToken",
  "removeUserRestriction",
  "replyToSupportTicket",
  "requestAccountDeletion",
  "requestPasswordReset",
  "resolveBookingDisputeV3",
  "restoreAccount",
  "retryProviderPayoutV3",
  "runBookingFinancialReconciliationV3",
  "runProviderPayoutProcessingBatchV3",
  "listOfferWallCampaigns",
  "sendAdminPromotionalNotification",
  "sendChatMessage",
  "sendProviderRequestRemindersV3",
  "sendPushForNotification",
  "sendTestPushToSelf",
  "setOfferWallCampaignStatus",
  "setOfferCampaignStatus",
  "startDirectUserChat",
  "startProviderChat",
  "submitBookingReviewV3",
  "syncAuthIdentity",
  "syncNotificationToken",
  "syncProfileFollowCounts",
  "syncProviderServicesOnVerificationUpdate",
  "syncServiceSlots",
  "syncSocialPostFeedMetadata",
  "acknowledgeOfferWallDisplay",
  "createOfferWallCampaign",
  "updateOfferCampaign",
  "updateOfferWallCampaign",
  "verifyBookingPaymentV3",
  "verifyBookingStartOtpV3",
].sort();

const intentionallyUnexportedBookingV3Names = [].sort();

test("compiled function exports match the production baseline", async () => {
  const moduleExports = require("../lib/index.js");
  const actualExportNames = Object.keys(moduleExports).sort();

  assert.deepStrictEqual(actualExportNames, expectedExportNames);
  for (const name of intentionallyUnexportedBookingV3Names) {
    assert.equal(moduleExports[name], undefined, `${name} should remain unexported`);
  }
});
