// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy_ZN8EJkIuhKyKeoAek329o52BZJCJFo',
    appId: '1:81944777235:web:4a59101805f7bdd611a5e6',
    messagingSenderId: '81944777235',
    projectId: 'pettexo-d9409',
    authDomain: 'pettexo-d9409.firebaseapp.com',
    storageBucket: 'pettexo-d9409.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGEyEsh8nK2IVQqKLR_5lplDedLY-yo3Y',
    appId: '1:81944777235:android:83240b20e11881ee11a5e6',
    messagingSenderId: '81944777235',
    projectId: 'pettexo-d9409',
    storageBucket: 'pettexo-d9409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXEs84ZPaGmfg7mg48pAREjFvXAxRTrXg',
    appId: '1:81944777235:ios:0d2059a6ccaeaa2f11a5e6',
    messagingSenderId: '81944777235',
    projectId: 'pettexo-d9409',
    storageBucket: 'pettexo-d9409.firebasestorage.app',
    iosBundleId: 'com.pettexo.app',
  );
}
