export const ACCEPT_WINDOW_MINUTES = 60;
export const PAY_WINDOW_MINUTES = 60;
export const BUFFER_MINUTES = 30;
export const RUNWAY_MINUTES = 150;
export const DEFAULT_PROVIDER_TIMEZONE = "Asia/Kolkata";
export const PLATFORM_COMMISSION_BASIS_POINTS = 1500;

export const MINUTE_IN_MS = 60 * 1000;
export const ACCEPT_WINDOW_MS = ACCEPT_WINDOW_MINUTES * MINUTE_IN_MS;
export const PAY_WINDOW_MS = PAY_WINDOW_MINUTES * MINUTE_IN_MS;
export const BUFFER_MS = BUFFER_MINUTES * MINUTE_IN_MS;
export const RUNWAY_MS = RUNWAY_MINUTES * MINUTE_IN_MS;

if (RUNWAY_MINUTES !== ACCEPT_WINDOW_MINUTES + PAY_WINDOW_MINUTES + BUFFER_MINUTES) {
  throw new Error(
    "RUNWAY_MINUTES must equal ACCEPT_WINDOW_MINUTES + PAY_WINDOW_MINUTES + BUFFER_MINUTES.",
  );
}
